import { Worker, Complaint, Facility } from './types';

export const workers: Worker[] = [
  {
    workerId: 'W001',
    name: 'Amit Kumar',
    area: 'Sector 15, Chandigarh',
    trainingPhase: 'Completed',
    tasksCompleted: 128,
    performance: 92,
    location: { lat: 30.7333, lng: 76.7794 },
    skills: ['Hazardous Waste Handling', 'Recycling Sorting'],
  },
  {
    workerId: 'W002',
    name: 'Priya Sharma',
    area: 'Sector 22, Chandigarh',
    trainingPhase: 'Phase 2',
    tasksCompleted: 75,
    performance: 88,
    location: { lat: 30.7291, lng: 76.7821 },
    skills: ['Composting', 'Organic Waste'],
  },
  {
    workerId: 'W003',
    name: 'Rahul Verma',
    area: 'Sector 35, Chandigarh',
    trainingPhase: 'Completed',
    tasksCompleted: 150,
    performance: 95,
    location: { lat: 30.7214, lng: 76.7699 },
    skills: ['Heavy Machinery Operation', 'Recycling Sorting'],
  },
  {
    workerId: 'W004',
    name: 'Sunita Devi',
    area: 'Sector 45, Chandigarh',
    trainingPhase: 'Phase 1',
    tasksCompleted: 32,
    performance: 81,
    location: { lat: 30.707, lng: 76.7649 },
    skills: ['General Waste Collection'],
  },
  {
    workerId: 'W005',
    name: 'Manoj Singh',
    area: 'Manimajra, Chandigarh',
    trainingPhase: 'Completed',
    tasksCompleted: 110,
    performance: 90,
    location: { lat: 30.7389, lng: 76.843 },
    skills: ['Hazardous Waste Handling', 'Scrap Collection'],
  },
];

export const complaints: Complaint[] = [
  {
    id: 'C001',
    userName: 'Rajesh Gupta',
    userPhotoUrl: 'https://picsum.photos/seed/user1/40/40',
    location: 'Near Elante Mall',
    wasteCategory: 'Mixed',
    status: 'Completed',
    assignedWorker: 'Amit Kumar',
    createdAt: '2024-07-20T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint1/600/400',
  },
  {
    id: 'C002',
    userName: 'Anita Desai',
    userPhotoUrl: 'https://picsum.photos/seed/user2/40/40',
    location: 'Sukhna Lake Park',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-21T11:30:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint2/600/400',
  },
  {
    id: 'C003',
    userName: 'Vikram Batra',
    userPhotoUrl: 'https://picsum.photos/seed/user3/40/40',
    location: 'IT Park Road',
    wasteCategory: 'Organic',
    status: 'In Progress',
    assignedWorker: 'Priya Sharma',
    createdAt: '2024-07-21T09:15:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint3/600/400',
  },
  {
    id: 'C004',
    userName: 'Sonia Mehta',
    userPhotoUrl: 'https://picsum.photos/seed/user4/40/40',
    location: 'Sector 17 Market',
    wasteCategory: 'Hazardous',
    status: 'Pending',
    createdAt: '2024-07-22T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint4/600/400',
  },
  {
    id: 'C005',
    userName: 'Karan Johar',
    userPhotoUrl: 'https://picsum.photos/seed/user5/40/40',
    location: 'Rock Garden',
    wasteCategory: 'Mixed',
    status: 'Completed',
    assignedWorker: 'Rahul Verma',
    createdAt: '2024-07-19T14:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint5/600/400',
  },
  {
    id: 'C006',
    userName: 'Aarav Sharma',
    userPhotoUrl: 'https://picsum.photos/seed/user6/40/40',
    location: 'Connaught Place, Delhi',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-23T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint6/600/400',
  },
  {
    id: 'C007',
    userName: 'Isha Singh',
    userPhotoUrl: 'https://picsum.photos/seed/user7/40/40',
    location: 'Chandni Chowk, Delhi',
    wasteCategory: 'Mixed',
    status: 'In Progress',
    assignedWorker: 'W001',
    createdAt: '2024-07-23T11:20:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint7/600/400',
  },
  {
    id: 'C008',
    userName: 'Rohan Mehra',
    userPhotoUrl: 'https://picsum.photos/seed/user8/40/40',
    location: 'India Gate, Delhi',
    wasteCategory: 'Organic',
    status: 'Completed',
    assignedWorker: 'W002',
    createdAt: '2024-07-22T15:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint8/600/400',
  },
  {
    id: 'C009',
    userName: 'Diya Gupta',
    userPhotoUrl: 'https://picsum.photos/seed/user9/40/40',
    location: 'Hauz Khas Village, Delhi',
    wasteCategory: 'Hazardous',
    status: 'Pending',
    createdAt: '2024-07-23T14:10:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint9/600/400',
  },
  {
    id: 'C010',
    userName: 'Kabir Khan',
    userPhotoUrl: 'https://picsum.photos/seed/user10/40/40',
    location: 'Khan Market, Delhi',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-24T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint10/600/400',
  },
  {
    id: 'C011',
    userName: 'Myra Reddy',
    userPhotoUrl: 'https://picsum.photos/seed/user11/40/40',
    location: 'Lodhi Garden, Delhi',
    wasteCategory: 'Organic',
    status: 'In Progress',
    assignedWorker: 'W003',
    createdAt: '2024-07-24T10:30:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint11/600/400',
  },
  {
    id: 'C012',
    userName: 'Arjun Patel',
    userPhotoUrl: 'https://picsum.photos/seed/user12/40/40',
    location: 'Qutub Minar, Delhi',
    wasteCategory: 'Mixed',
    status: 'Completed',
    assignedWorker: 'W001',
    createdAt: '2024-07-22T18:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint12/600/400',
  },
  {
    id: 'C013',
    userName: 'Saanvi Jain',
    userPhotoUrl: 'https://picsum.photos/seed/user13/40/40',
    location: 'Red Fort, Delhi',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-24T12:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint13/600/400',
  },
  {
    id: 'C014',
    userName: 'Vihaan Kumar',
    userPhotoUrl: 'https://picsum.photos/seed/user14/40/40',
    location: 'Humayun\'s Tomb, Delhi',
    wasteCategory: 'Organic',
    status: 'Pending',
    createdAt: '2024-07-24T13:45:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint14/600/400',
  },
  {
    id: 'C015',
    userName: 'Ananya Iyer',
    userPhotoUrl: 'https://picsum.photos/seed/user15/40/40',
    location: 'Akshardham Temple, Delhi',
    wasteCategory: 'Mixed',
    status: 'In Progress',
    assignedWorker: 'W004',
    createdAt: '2024-07-24T15:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint15/600/400',
  },
  {
    id: 'C016',
    userName: 'Advik Nair',
    userPhotoUrl: 'https://picsum.photos/seed/user16/40/40',
    location: 'Nehru Place, Delhi',
    wasteCategory: 'Hazardous',
    status: 'Completed',
    assignedWorker: 'W005',
    createdAt: '2024-07-23T09:30:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint16/600/400',
  },
  {
    id: 'C017',
    userName: 'Zara Das',
    userPhotoUrl: 'https://picsum.photos/seed/user17/40/40',
    location: 'Sarojini Nagar Market, Delhi',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-25T08:30:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint17/600/400',
  },
  {
    id: 'C018',
    userName: 'Reyansh Joshi',
    userPhotoUrl: 'https://picsum.photos/seed/user18/40/40',
    location: 'Lotus Temple, Delhi',
    wasteCategory: 'Organic',
    status: 'Pending',
    createdAt: '2024-07-25T10:15:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint18/600/400',
  },
  {
    id: 'C019',
    userName: 'Anika Pillai',
    userPhotoUrl: 'https://picsum.photos/seed/user19/40/40',
    location: 'Dilli Haat, Delhi',
    wasteCategory: 'Mixed',
    status: 'In Progress',
    assignedWorker: 'W002',
    createdAt: '2024-07-25T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint19/600/400',
  },
  {
    id: 'C020',
    userName: 'Krish Menon',
    userPhotoUrl: 'https://picsum.photos/seed/user20/40/40',
    location: 'Garden of Five Senses, Delhi',
    wasteCategory: 'Organic',
    status: 'Completed',
    assignedWorker: 'W003',
    createdAt: '2024-07-24T16:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint20/600/400',
  },
  {
    id: 'C021',
    userName: 'Aisha Kapoor',
    userPhotoUrl: 'https://picsum.photos/seed/user21/40/40',
    location: 'Jama Masjid, Delhi',
    wasteCategory: 'Mixed',
    status: 'Pending',
    createdAt: '2024-07-25T13:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint21/600/400',
  },
  {
    id: 'C022',
    userName: 'Vivaan Malhotra',
    userPhotoUrl: 'https://picsum.photos/seed/user22/40/40',
    location: 'Rajpath, Delhi',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-25T14:20:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint22/600/400',
  },
  {
    id: 'C023',
    userName: 'Kiara Rao',
    userPhotoUrl: 'https://picsum.photos/seed/user23/40/40',
    location: 'Agrasen ki Baoli, Delhi',
    wasteCategory: 'Mixed',
    status: 'In Progress',
    assignedWorker: 'W001',
    createdAt: '2024-07-25T16:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint23/600/400',
  },
  {
    id: 'C024',
    userName: 'Ishaan Aggarwal',
    userPhotoUrl: 'https://picsum.photos/seed/user24/40/40',
    location: 'National Rail Museum, Delhi',
    wasteCategory: 'Hazardous',
    status: 'Completed',
    assignedWorker: 'W005',
    createdAt: '2024-07-24T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint24/600/400',
  },
  {
    id: 'C025',
    userName: 'Pari Choudhary',
    userPhotoUrl: 'https://picsum.photos/seed/user25/40/40',
    location: 'Shankar\'s International Dolls Museum, Delhi',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-25T17:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint25/600/400',
  },
];

export const facilities: Facility[] = [
  {
    id: 'F001',
    name: 'Chandigarh Recycling Hub',
    type: 'Recycling Center',
    location: 'Industrial Area Phase 1',
  },
  {
    id: 'F002',
    name: 'Green Earth Compost',
    type: 'Compost Plant',
    location: 'Dadu Majra Colony',
  },
  {
    id: 'F003',
    name: 'City Scrap Dealers',
    type: 'Scrap Shop',
    location: 'Sector 26',
  },
];

export const complaintsByDay = [
    { date: "2024-07-15", "Completed": 20, "Pending": 5, "In Progress": 3 },
    { date: "2024-07-16", "Completed": 25, "Pending": 3, "In Progress": 5 },
    { date: "2024-07-17", "Completed": 22, "Pending": 8, "In Progress": 4 },
    { date: "2024-07-18", "Completed": 30, "Pending": 4, "In Progress": 6 },
    { date: "2024-07-19", "Completed": 28, "Pending": 6, "In Progress": 7 },
    { date: "2024-07-20", "Completed": 35, "Pending": 2, "In Progress": 5 },
    { date: "2024-07-21", "Completed": 32, "Pending": 5, "In Progress": 8 },
];
