import { Worker, Complaint, Facility } from './types';

export const workers: Worker[] = [
  {
    workerId: 'W001',
    name: 'Amit Kumar',
    area: 'Sector 15, Chandigarh',
    trainingPhase: 'Completed',
    tasksCompleted: 128,
    performance: 92,
    location: { lat: 30.7333, lng: 76.7794 },
    skills: ['Hazardous Waste Handling', 'Recycling Sorting'],
  },
  {
    workerId: 'W002',
    name: 'Priya Sharma',
    area: 'Sector 22, Chandigarh',
    trainingPhase: 'Phase 2',
    tasksCompleted: 75,
    performance: 88,
    location: { lat: 30.7291, lng: 76.7821 },
    skills: ['Composting', 'Organic Waste'],
  },
  {
    workerId: 'W003',
    name: 'Rahul Verma',
    area: 'Sector 35, Chandigarh',
    trainingPhase: 'Completed',
    tasksCompleted: 150,
    performance: 95,
    location: { lat: 30.7214, lng: 76.7699 },
    skills: ['Heavy Machinery Operation', 'Recycling Sorting'],
  },
  {
    workerId: 'W004',
    name: 'Sunita Devi',
    area: 'Sector 45, Chandigarh',
    trainingPhase: 'Phase 1',
    tasksCompleted: 32,
    performance: 81,
    location: { lat: 30.707, lng: 76.7649 },
    skills: ['General Waste Collection'],
  },
  {
    workerId: 'W005',
    name: 'Manoj Singh',
    area: 'Manimajra, Chandigarh',
    trainingPhase: 'Completed',
    tasksCompleted: 110,
    performance: 90,
    location: { lat: 30.7389, lng: 76.843 },
    skills: ['Hazardous Waste Handling', 'Scrap Collection'],
  },
];

export const complaints: Complaint[] = [
  {
    id: 'C001',
    userName: 'Rajesh Gupta',
    userPhotoUrl: 'https://picsum.photos/seed/user1/40/40',
    location: 'Near Elante Mall',
    wasteCategory: 'Mixed',
    status: 'Completed',
    assignedWorker: 'Amit Kumar',
    createdAt: '2024-07-20T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint1/600/400',
  },
  {
    id: 'C002',
    userName: 'Anita Desai',
    userPhotoUrl: 'https://picsum.photos/seed/user2/40/40',
    location: 'Sukhna Lake Park',
    wasteCategory: 'Recyclable',
    status: 'Pending',
    createdAt: '2024-07-21T11:30:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint2/600/400',
  },
  {
    id: 'C003',
    userName: 'Vikram Batra',
    userPhotoUrl: 'https://picsum.photos/seed/user3/40/40',
    location: 'IT Park Road',
    wasteCategory: 'Organic',
    status: 'In Progress',
    assignedWorker: 'Priya Sharma',
    createdAt: '2024-07-21T09:15:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint3/600/400',
  },
  {
    id: 'C004',
    userName: 'Sonia Mehta',
    userPhotoUrl: 'https://picsum.photos/seed/user4/40/40',
    location: 'Sector 17 Market',
    wasteCategory: 'Hazardous',
    status: 'Pending',
    createdAt: '2024-07-22T08:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint4/600/400',
  },
  {
    id: 'C005',
    userName: 'Karan Johar',
    userPhotoUrl: 'https://picsum.photos/seed/user5/40/40',
    location: 'Rock Garden',
    wasteCategory: 'Mixed',
    status: 'Completed',
    assignedWorker: 'Rahul Verma',
    createdAt: '2024-07-19T14:00:00Z',
    imageUrl: 'https://picsum.photos/seed/complaint5/600/400',
  },
];

export const facilities: Facility[] = [
  {
    id: 'F001',
    name: 'Chandigarh Recycling Hub',
    type: 'Recycling Center',
    location: 'Industrial Area Phase 1',
  },
  {
    id: 'F002',
    name: 'Green Earth Compost',
    type: 'Compost Plant',
    location: 'Dadu Majra Colony',
  },
  {
    id: 'F003',
    name: 'City Scrap Dealers',
    type: 'Scrap Shop',
    location: 'Sector 26',
  },
];

export const complaintsByDay = [
    { date: "2024-07-15", "Completed": 20, "Pending": 5, "In Progress": 3 },
    { date: "2024-07-16", "Completed": 25, "Pending": 3, "In Progress": 5 },
    { date: "2024-07-17", "Completed": 22, "Pending": 8, "In Progress": 4 },
    { date: "2024-07-18", "Completed": 30, "Pending": 4, "In Progress": 6 },
    { date: "2024-07-19", "Completed": 28, "Pending": 6, "In Progress": 7 },
    { date: "2024-07-20", "Completed": 35, "Pending": 2, "In Progress": 5 },
    { date: "2024-07-21", "Completed": 32, "Pending": 5, "In Progress": 8 },
];
